version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - 9090:80
    volumes:
      - ./config/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    depends_on: [bot, db]
  vue-dev:
    image: node:erbium
    volumes:
      - ./webui:/webui
      - ./.docker/webui/node_modules:/webui/node_modules
    networks:
      - frontend
    command: bash -c "cd /webui && yarn install --force && yarn dev"

networks:
  frontend:
  backend:
