version: '3.8'
services:
  db:
      image: mongo:4.2.8-bionic
      volumes: 
        - ./.docker/db:/data/db
      networks:
        - backend

  bot:
    image: node:erbium
    volumes:
      - ./bot:/vixen
      - ./.docker/bot/node_modules:/vixen/node_modules
      - ./.docker/bot/data:/vixen/data
    networks:
      - frontend
      - backend
    command: bash -c "cd /vixen && yarn install --force && node /vixen/index.js"
    depends_on: [db]
    tty: true

  webui:
    image: nginx:latest
    ports:
      - 9090:80
    volumes:
      - ./webui/dist:/var/www/html
    networks:
      - frontend

networks:
  frontend:
  backend: